# Generated by Django 5.2.15 on 2026-08-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WellFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_uwi', models.TextField(db_index=True, unique=True)),
                ('user_format_well_id', models.TextField(blank=True, null=True)),
                ('uwi_suffix', models.SmallIntegerField(blank=True, null=True)),
                ('loc_exc_code', models.SmallIntegerField(blank=True, null=True)),
                ('legal_subdivisions', models.SmallIntegerField(blank=True, null=True)),
                ('section', models.SmallIntegerField(blank=True, null=True)),
                ('township', models.SmallIntegerField(blank=True, null=True)),
                ('range', models.SmallIntegerField(blank=True, null=True)),
                ('meridian', models.SmallIntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('well_status_text', models.TextField(blank=True, null=True)),
                ('perforation_top_depth_md', models.FloatField(blank=True, null=True)),
                ('perforation_date', models.IntegerField(blank=True, null=True)),
                ('perforation_type', models.IntegerField(blank=True, choices=[(0, 'Undefined'), (1, 'Treat'), (2, 'Perf'), (3, 'Frac'), (4, 'Openhole'), (5, 'Plug'), (6, 'Liner')], null=True)),
                ('govt_reported_type', models.TextField(blank=True, null=True)),
                ('deepest_casing_type', models.IntegerField(blank=True, choices=[(0, 'Unknown'), (1, 'Intermediate'), (2, 'Production'), (3, 'Liner'), (4, 'Surface'), (5, 'Conductor')], null=True)),
                ('deepest_casing_depth', models.FloatField(blank=True, null=True)),
                ('deepest_casing_size', models.FloatField(blank=True, null=True)),
                ('deepest_casing_weight', models.FloatField(blank=True, null=True)),
                ('deepest_casing_grade', models.TextField(blank=True, null=True)),
                ('md_all_wells', models.FloatField(blank=True, null=True)),
                ('tvd_m', models.FloatField(blank=True, null=True)),
                ('lateral_length_m', models.FloatField(blank=True, null=True)),
                ('months_since_last_prod', models.IntegerField(blank=True, null=True)),
                ('months_since_last_inj', models.IntegerField(blank=True, null=True)),
                ('idle_well_flag', models.BooleanField(blank=True, null=True)),
                ('depth_for_available_volume', models.FloatField(blank=True, null=True)),
                ('max_casing_volume_m3', models.FloatField(blank=True, null=True)),
                ('available_wellbore_volume_m3', models.FloatField(blank=True, null=True)),
                ('normalized_available_volume', models.FloatField(blank=True, null=True)),
                ('pressure_grade', models.FloatField(blank=True, null=True)),
                ('casing_burst_rating_psi', models.FloatField(blank=True, null=True)),
                ('percentage_top_depth_md_tvd', models.FloatField(blank=True, null=True)),
                ('usable_air_mass', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'well_feature',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='well_featur_latitud_a13a8c_idx')],
            },
        ),
    ]
