# Generated by Django 5.2.15 on 2026-08-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellstor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_code', models.TextField(db_index=True, unique=True)),
                ('facility_name', models.TextField(blank=True, null=True)),
                ('land_location', models.TextField(blank=True, null=True)),
                ('township', models.SmallIntegerField(blank=True, null=True)),
                ('range', models.SmallIntegerField(blank=True, null=True)),
                ('meridian', models.SmallIntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('capacity_mw', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'substation',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='substation_latitud_f13b25_idx')],
            },
        ),
    ]
