# Generated by Django 5.2.15 on 2026-08-04 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellstor', '0002_substation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellStorPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_uwi', models.TextField(db_index=True)),
                ('distance_m', models.FloatField(blank=True, null=True)),
                ('airmass', models.FloatField(blank=True, null=True)),
                ('good_probability', models.FloatField(blank=True, null=True)),
                ('wellstore_candidate', models.BooleanField(blank=True, null=True)),
                ('radius_m', models.FloatField(blank=True, null=True)),
                ('model_version', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nearest_substation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='well_predictions', to='wellstor.substation')),
            ],
            options={
                'db_table': 'wellstor_prediction',
                'indexes': [models.Index(fields=['base_uwi', 'radius_m'], name='wellstor_pr_base_uw_5aba75_idx')],
            },
        ),
    ]
