# Generated by Django 5.2.15 on 2026-08-04 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellstor', '0003_wellstorprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substation_candidate', models.BooleanField(blank=True, null=True)),
                ('suitable_probability', models.FloatField(blank=True, null=True)),
                ('min_suitable_radius_m', models.FloatField(blank=True, null=True)),
                ('suitable_radius', models.FloatField(blank=True, null=True)),
                ('average_distance', models.FloatField(blank=True, null=True)),
                ('well_count', models.IntegerField(blank=True, null=True)),
                ('good_count', models.IntegerField(blank=True, null=True)),
                ('total_volume', models.FloatField(blank=True, null=True)),
                ('total_airmass', models.FloatField(blank=True, null=True)),
                ('baseline_air_mass', models.FloatField(blank=True, null=True)),
                ('usable_air_mass', models.FloatField(blank=True, null=True)),
                ('energy_storage_mwh', models.FloatField(blank=True, null=True)),
                ('max_pressure', models.FloatField(blank=True, null=True)),
                ('min_pressure', models.FloatField(blank=True, null=True)),
                ('middle_pressure', models.FloatField(blank=True, null=True)),
                ('model_version', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('substation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_predictions', to='wellstor.substation')),
            ],
            options={
                'db_table': 'region_prediction',
            },
        ),
        migrations.CreateModel(
            name='RegionRadiusResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius_m', models.FloatField(blank=True, null=True)),
                ('average_distance', models.FloatField(blank=True, null=True)),
                ('well_count', models.IntegerField(blank=True, null=True)),
                ('good_count', models.IntegerField(blank=True, null=True)),
                ('total_volume', models.FloatField(blank=True, null=True)),
                ('total_airmass', models.FloatField(blank=True, null=True)),
                ('max_pressure', models.FloatField(blank=True, null=True)),
                ('min_pressure', models.FloatField(blank=True, null=True)),
                ('middle_pressure', models.FloatField(blank=True, null=True)),
                ('suitable_probability', models.FloatField(blank=True, null=True)),
                ('substation_candidate', models.BooleanField(blank=True, null=True)),
                ('prediction_source', models.TextField(blank=True, null=True)),
                ('prediction_reason', models.TextField(blank=True, null=True)),
                ('model_version', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('substation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_radius_results', to='wellstor.substation')),
            ],
            options={
                'db_table': 'region_radius_result',
                'indexes': [models.Index(fields=['substation', 'radius_m'], name='region_radi_substat_272a3e_idx')],
            },
        ),
    ]
