# Generated by Django 5.2.15 on 2026-08-04 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellstor', '0004_regionprediction_regionradiusresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellTrainingLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_uwi', models.TextField(db_index=True)),
                ('label', models.IntegerField(blank=True, null=True)),
                ('source_file', models.TextField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'well_training_label',
            },
        ),
        migrations.CreateModel(
            name='ModelFeatureWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.TextField()),
                ('model_version', models.TextField()),
                ('feature', models.TextField()),
                ('weight', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'model_feature_weight',
                'indexes': [models.Index(fields=['model_name', 'model_version'], name='model_featu_model_n_57fdc1_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegionTrainingLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius_m', models.FloatField(blank=True, null=True)),
                ('well_counts', models.IntegerField(blank=True, null=True)),
                ('good_count', models.IntegerField(blank=True, null=True)),
                ('total_volume', models.FloatField(blank=True, null=True)),
                ('total_airmass', models.FloatField(blank=True, null=True)),
                ('average_distance', models.FloatField(blank=True, null=True)),
                ('max_pressure', models.FloatField(blank=True, null=True)),
                ('min_pressure', models.FloatField(blank=True, null=True)),
                ('middle_pressure', models.FloatField(blank=True, null=True)),
                ('region_label', models.IntegerField(blank=True, null=True)),
                ('suitable_radius_m', models.FloatField(blank=True, null=True)),
                ('source_file', models.TextField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('substation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_training_labels', to='wellstor.substation')),
            ],
            options={
                'db_table': 'region_training_label',
                'indexes': [models.Index(fields=['substation', 'radius_m'], name='region_trai_substat_a0f972_idx')],
            },
        ),
    ]
